name: advanced2
channels:
  - conda-forge
dependencies:
  - folium
  - jinja2
  - osmnx
  - matplotlib
  - pandas=
  - geopandas
  - descartes
  - shapely
  - poppler
  - numpy
  - scipy
  - scikit-spatial
  - alphashape
